name: CI

on: [push]

env:
  CC: gcc-10
  CXX: g++-10
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        git submodule update --init --rebase -- cmake
        cmake -E make_directory ${{github.workspace}}/build
    - name: Install GCC 10
      shell: bash
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra"
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -V -C $BUILD_TYPE
